version: '2'

services:
  webserver:
    build: ./docker/webserver
    image: php_env_test
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/num1r0/workspace/development/docker-php/www:/var/www/html
    links:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=db_php_env_test